# Generated by Django 5.2 on 2025-04-06 22:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='price_per_person',
        ),
        migrations.RenameField(
            model_name='tourpackage',
            old_name='price',
            new_name='price_per_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('company', 'Company')], default='tour', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='would_recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='ai_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_group_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='min_group_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('party', 'Party'), ('family', 'Family'), ('dj_night', 'DJ Night'), ('classical', 'Classical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='max_group_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='min_group_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('party', 'Party'), ('family', 'Family'), ('dj_night', 'DJ Night'), ('classical', 'Classical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tourpackage'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tours', to='core.tourtag'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='core.tourtag'),
        ),
        migrations.CreateModel(
            name='UserTourPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('preferred_tour_types', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
