# Generated by Django 5.2 on 2025-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tourtag_rename_price_tour_price_per_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in days', null=True),
        ),
    ]
