# Generated by Django 5.2 on 2025-04-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='availability',
            field=models.IntegerField(blank=True, help_text='Available spots', null=True),
        ),
    ]
