# Generated by Django 5.2 on 2025-04-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_created_at'),
        ('core', '0004_alter_tour_availability'),
    ]

    operations = [
    ]
