# Generated by Django 5.2 on 2025-04-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250409_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourimage',
            name='created_at',
        ),
    ]
