# Generated by Django 5.2 on 2025-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tourimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20),
        ),
    ]
