# Generated by Django 5.2 on 2025-04-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tour_end_date_tour_start_date_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
