# Generated by Django 5.2 on 2025-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tour_latitude_tour_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon'), ('spring', 'Spring')], max_length=10, null=True),
        ),
    ]
