# Generated by Django 5.2 on 2025-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tour_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('cultural', 'Cultural Immersion'), ('historical', 'Historical Exploration'), ('nature', 'Nature & Wildlife'), ('beach', 'Beach Getaway'), ('mountain', 'Mountain Expedition'), ('city_tour', 'City Sightseeing'), ('foodie', 'Food & Culinary'), ('luxury', 'Luxury Escape'), ('family', 'Family Fun')], max_length=20, null=True),
        ),
    ]
