# Generated by Django 5.2 on 2025-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tour_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('cultural', 'Cultural Immersion'), ('historical', 'Historical Exploration'), ('nature', 'Nature & Wildlife'), ('beach', 'Beach Getaway'), ('mountain', 'Mountain Expedition'), ('city_tour', 'City Sightseeing'), ('foodie', 'Food & Culinary'), ('luxury', 'Luxury Escape'), ('party', 'Party'), ('family', 'Family'), ('dj_night', 'DJ Night'), ('classical', 'Classical')], max_length=20, null=True),
        ),
    ]
